text = 'JNOCT HLTOB OIWHE LEWNV SROAA ETMHU UGTAU ASOYO TIBNB TDINN AFHIL STALN TEUAT EEYHA DMOEE TOHVV AIOOR ESWTO INDAA TAATI GIRKH OETAS ICAYN NGECA AURHC EIEDM TBLCK IEHWT NFPSA RBEST HELET NEHME IOUIS OOUTN ENTOE AARNY ENNBE OFGID NRCNE EPOMF TEOYE ODPGP OALCG AAHYS CNSAN ETNAN ELOTH ROASY UNEUI TAEIA ACUEE TFPRE ATFLA ALMID IADEE ETEWC URNUL HCMII ETISA ONNSA TSGON ERIRW RMFHU SHMGE EIGUL TROEL SITEC HTTIT ETSAT ISAWT IAAUC NYRCO RTGIL KSDFL HTEDI ETHYC REINE AHWRT MAENO HTYTE NSNEE HMICE EDORN HNISN AWSET OTECS GCRTN NCSTT EIENE SISWT OHTUL CANEC MTSIA AIIEH CRUCS SNOGS ESEAT VRLAH INOEO NHMAI DIHAE FCGTF EEASA EWAFU SUCSN AEAOW MLONH WEMSE LEXEH ETVNP IDAYT NMHWO LTFNO TNRWO BNAIF TDINC UTNEL TKKTA TNEEI RTAAA IEUWR TLEON ETTRT ADADE IICSD NRYTT NIIGE SATVH URPSD MROIO OIEIH NTHTU DTOUE EMELT EABIA GOECI UTNFO WMEOO DWSOA RATOF ROHTE ARDCE YAORB FIRBE HGALV ERASA HSIUL GNTIW ETRNE RGEHI FRETS SCKOM TBONU LFDIA HHSEF DHCEE YRGIT GAAEH VETAO ENYTS IEIEG ETDNT HTICI OMIHE NNBNF EIAIT OANEE OIHDI EAORN TLHGO EDSFO LGAIK IIHBI LIEAB HLROT STOTH IWEGE TOOWC AGAHR ANHRH IEIAU VIIEC EALII RDSOE HTTSO YELIS EETER MCNLN CKURT EEDHH ITDSL SONTI SSONH MIEES UIHWM IFUOH ORHNO YDETO OERON DEWGU RIAPO ELNOT TICCG EVFIU RLNCN SAAET WDCIR UAEUN DLENS IATRE NMNEH VOEOH PMIWS TPTES CMNTY EEIHL IXCWA ODEHE DPSEU AEERI UERNN AENUE TTCTU TDSCN TFVNC EMSWW ODXUO TTTKO TFMES LIIDE MNSDI TNAVT LODHT NMLOO GWTAL BHYII EHRCN DIDDO VTAHD ANACN CSAAL OUIHT OKHEO NSGDT SOSWH UPTSR EOUNG NWSHV ITEEY UITHV ALYNR THWTH TANCS DAEIG TBNZL IBTOS WTETR COROT MITEC ORAND ITDAM KOLEA NTDNA ERWRU WRSOA YSAAD EWGTE NVDTS UTYEF NTTMN ALOKE HHKOT AEAHE GUTAT EYNTI BETRL ABTDT SIEUP OGAEE IEPLS HBPEN OEITL CIEOR NFLAT SEIET LAGMN SNILA TETNW SBNWI LTILT ODIST THDCN RTTUU IIWRN TEGTO SWLIC ONGNH NYAOG SOBAL AOCGN HYRAT UTHOO IAEGD ALRHI RAIEO TETAO EAETJ RWSYL YUAIT EALFT LWTAA HRAVN ROHRS EVGEC OBICA ITRDO NIAES EHAEN GNTEE ERAUE EHOEL YTEOA OAIET ILBNI OADRI GTEYA ELNNI GDALN KNADT LETEW EENTE THPOY FCEER HOUOE EEOFT TUAAD MONIL ISTSH AAGNA ALUEI XUUNA HETDT VAKHI AGAON TNEND HEEOT PIAER RTERS TRNTR ETTCN EITPU KRSYE RIREE DEILH RISEO NTNEY GLDTL FSIAD OSFOH HIETI EAHRF YEIIE ETTFS AHTES SFSLR NEACO GHBTO RSEET EHINN NTUSW DHEEO HRIRS NDHTK LHACR ENHHL ANIYI RAS'


def charcount(text):
    with_spaces = len(text)
    text = ''.join(text.split(' '))
    print(f'With spaces: {with_spaces}')
    print(f'Without spaces: {len(text)}')


def factors(num):
    factor = []
    for i in range(num):
        if i == 0:
            pass
        elif num % i == 0:
            factor.append(i)

    print(f'The factors of {num} are {factor}')


charcount(text)
text = text.lower()
text = ''.join(text.split(' '))
print(text)
# factors(1883)
# l = 36 // 3

# col1 = text[:l+1]
# col2 = text[l:(2*l)+1]
# col3 = text[(2*l):]
# # col4 = text[(3*l):(4*l)+1]
# # col5 = text[(4*l):(5*l)+1]
# # col6 = text[(5*l):(6*l)+1]
# # col7 = text[(6*l):]

# for i in range(l):
#     print(
#         f'{col1[i]} {col2[i]} {col3[i]}')
