text = 'JNOCTHLTOBOIWHELEWNVSROAAETMHUUGTAUASOYOTIBNBTDINNAFHILSTALNTEUATEEYHADMOEETOHVVAIOORESWTOINDAATAATIGIRKHOETASICAYNNGECAAURHCEIEDMTBLCKIEHWTNFPSARBESTHELETNEHMEIOUISOOUTNENTOEAARNYENNBEOFGIDNRCNEEPOMFTEOYEODPGPOALCGAAHYSCNSANETNANELOTHROASYUNEUITAEIAACUEETFPREATFLAALMIDIADEEETEWCURNULHCMIIETISAONNSATSGONERIRWRMFHUSHMGEEIGULTROELSITECHTTITETSATISAWTIAAUCNYRCORTGILKSDFLHTEDIETHYCREINEAHWRTMAENOHTYTENSNEEHMICEEDORNHNISNAWSETOTECSGCRTNNCSTTEIENESISWTOHTULCANECMTSIAAIIEHCRUCSSNOGSESEATVRLAHINOEONHMAIDIHAEFCGTFEEASAEWAFUSUCSNAEAOWMLONHWEMSELEXEHETVNPIDAYTNMHWOLTFNOTNRWOBNAIFTDINCUTNELTKKTATNEEIRTAAAIEUWRTLEONETTRTADADEIICSDNRYTTNIIGESATVHURPSDMROIOOIEIHNTHTUDTOUEEMELTEABIAGOECIUTNFOWMEOODWSOARATOFROHTEARDCEYAORBFIRBEHGALVERASAHSIULGNTIWETRNERGEHIFRETSSCKOMTBONULFDIAHHSEFDHCEEYRGITGAAEHVETAOENYTSIEIEGETDNTHTICIOMIHENNBNFEIAITOANEEOIHDIEAORNTLHGOEDSFOLGAIKIIHBILIEABHLROTSTOTHIWEGETOOWCAGAHRANHRHIEIAUVIIECEALIIRDSOEHTTSOYELISEETERMCNLNCKURTEEDHHITDSLSONTISSONHMIEESUIHWMIFUOHORHNOYDETOOERONDEWGURIAPOELNOTTICCGEVFIURLNCNSAAETWDCIRUAEUNDLENSIATRENMNEHVOEOHPMIWSTPTESCMNTYEEIHLIXCWAODEHEDPSEUAEERIUERNNAENUETTCTUTDSCNTFVNCEMSWWODXUOTTTKOTFMESLIIDEMNSDITNAVTLODHTNMLOOGWTALBHYIIEHRCNDIDDOVTAHDANACNCSAALOUIHTOKHEONSGDTSOSWHUPTSREOUNGNWSHVITEEYUITHVALYNRTHWTHTANCSDAEIGTBNZLIBTOSWTETRCOROTMITECORANDITDAMKOLEANTDNAERWRUWRSOAYSAADEWGTENVDTSUTYEFNTTMNALOKEHHKOTAEAHEGUTATEYNTIBETRLABTDTSIEUPOGAEEIEPLSHBPENOEITLCIEORNFLATSEIETLAGMNSNILATETNWSBNWILTILTODISTTHDCNRTTUUIIWRNTEGTOSWLICONGNHNYAOGSOBALAOCGNHYRATUTHOOIAEGDALRHIRAIEOTETAOEAETJRWSYLYUAITEALFTLWTAAHRAVNROHRSEVGECOBICAITRDONIAESEHAENGNTEEERAUEEHOELYTEOAOAIETILBNIOADRIGTEYAELNNIGDALNKNADTLETEWEENTETHPOYFCEERHOUOEEEOFTTUAADMONILISTSHAAGNAALUEIXUUNAHETDTVAKHIAGAONTNENDHEEOTPIAERRTERSTRNTRETTCNEITPUKRSYERIREEDEILHRISEONTNEYGLDTLFSIADOSFOHHIETIEAHRFYEIIEETTFSAHTESSFSLRNEACOGHBTORSEETEHINNNTUSWDHEEOHRIRSNDHTKLHACRENHHLANIYIRAS'


def charcount(text):
    with_spaces = len(text)
    text = ''.join(text.split(' '))
    print(f'With spaces: {with_spaces}')
    print(f'Without spaces: {len(text)}')


def factors(num):
    factor = []
    for i in range(num):
        if i == 0:
            pass
        elif num % i == 0:
            factor.append(i)

    print(f'The factors of {num} are {factor}')


l = 1883 // 3
col1 = text[:l+1]
col2 = text[l:(2*l)+1]
col3 = text[(2*l):]
col4 = text[(3*l):(4*l)+1]
col5 = text[(4*l):(5*l)+1]
col6 = text[(5*l):(6*l)+1]
# col7 = text[(6*l):]

for i in range(l):
    print(
        f'{col1[i]} {col2[i]} {col3[i]}')
